#!/usr/bin/env python3
"""V.2 store-buffering (SB) litmus generator — §Phase 7 domain-validation track.

    generate.py <tso|sc> <out_dir>

Emits an explicit-state CTXDSL model of the classic 2-thread store-buffering
litmus test + a verify.toml, for one memory model:

  Thread 0:  x = 1;  r0 = y      Thread 1:  y = 1;  r1 = x
  (init x = y = 0)

The litmus question is whether the outcome `r0 == 0 && r1 == 0` is
observable. Textbook result (herd / rmem / any MCM reference):
  - **SC** (sequential consistency, or TSO + a fence between the write and
    the read): r0=r1=0 is **FORBIDDEN**.
  - **TSO** (x86-TSO store buffers, no fence): r0=r1=0 is **ALLOWED** — each
    thread's write sits in its private store buffer, so each read can see
    the other location's stale 0 before the buffer drains.

So `reachable(BothReadZero)` is the discriminating verdict:
  TSO ⇒ true   (the relaxation is observable),
  SC  ⇒ false  (SC / the fence forbids it).

**Why explicit states, not variables.** mununu's `verify` + mu-calculus
path binds predicates to **state names**, not to CTXDSL variable *values*
(`r0 == 0` atoms do not bind through the verify composition path — verified
2026-06-23). So the model encodes memory / store-buffer / read-result
configuration in the state name, and the both-zero outcome is a dedicated
absorbing state `BothReadZero` checked by the `reachable` template.

The model is a generated design-pattern demonstration of the memory-
consistency domain (cross-checked against the textbook SB result), NOT a
finding about a real processor (claims-integrity).

Operational state = (mx, my, sb0, sb1, p0, p1, r0, r1):
  mx,my  ∈ {0,1}   committed memory values
  sb0,sb1∈ {0,1}   store-buffer pending (TSO only; SC writes commit directly)
  p0,p1  ∈ {W,R,D} per-thread program counter (write / read / done)
  r0,r1  ∈ {n,0,1} read results (n = not yet read)
Events: w0 d0 r0 w1 d1 r1 (TSO) / w0 r0 w1 r1 (SC); commit → outcome state.
"""
import sys
import os
from collections import deque

INIT = (0, 0, 0, 0, "W", "W", "n", "n")


def succ_tso(s):
    mx, my, sb0, sb1, p0, p1, r0, r1 = s
    out = []
    if p0 == "W":
        out.append(("w0", (mx, my, 1, sb1, "R", p1, r0, r1)))      # buffer x=1
    if sb0 == 1:
        out.append(("d0", (1, my, 0, sb1, p0, p1, r0, r1)))        # drain x to mem
    if p0 == "R":
        out.append(("r0", (mx, my, sb0, sb1, "D", p1, my, r1)))    # read y from mem
    if p1 == "W":
        out.append(("w1", (mx, my, sb0, 1, p0, "R", r0, r1)))      # buffer y=1
    if sb1 == 1:
        out.append(("d1", (mx, 1, sb0, 0, p0, p1, r0, r1)))        # drain y to mem
    if p1 == "R":
        out.append(("r1", (mx, my, sb0, sb1, p0, "D", r0, mx)))    # read x from mem
    return out


def succ_sc(s):
    # SC / fenced: a write commits to memory immediately (the fence forces
    # the store buffer to drain before the following read), so there is no
    # pending-buffer window. sb0/sb1 stay 0.
    mx, my, _sb0, _sb1, p0, p1, r0, r1 = s
    out = []
    if p0 == "W":
        out.append(("w0", (1, my, 0, 0, "R", p1, r0, r1)))         # x=1 commits now
    if p0 == "R":
        out.append(("r0", (mx, my, 0, 0, "D", p1, my, r1)))
    if p1 == "W":
        out.append(("w1", (mx, 1, 0, 0, p0, "R", r0, r1)))         # y=1 commits now
    if p1 == "R":
        out.append(("r1", (mx, my, 0, 0, p0, "D", r0, mx)))
    return out


def name(s):
    mx, my, sb0, sb1, p0, p1, r0, r1 = s
    return f"S_mx{mx}my{my}sb{sb0}{sb1}p{p0}{p1}r{r0}{r1}"


def generate(model):
    succ = succ_tso if model == "tso" else succ_sc
    # BFS the operational model from INIT.
    seen = {INIT}
    edges = []          # (src_state, label, dst_state)
    commits = []        # (terminal_state, outcome_name)
    q = deque([INIT])
    while q:
        s = q.popleft()
        _mx, _my, _sb0, _sb1, p0, p1, r0, r1 = s
        if p0 == "D" and p1 == "D":
            outcome = "BothReadZero" if (r0 == 0 and r1 == 0) else "OtherOutcome"
            commits.append((s, outcome))
            continue
        for lbl, t in succ(s):
            edges.append((s, lbl, t))
            if t not in seen:
                seen.add(t)
                q.append(t)
    return seen, edges, commits


def emit_ctxdsl(model, seen, edges, commits):
    # Collect labels actually used.
    labels = sorted({lbl for (_s, lbl, _t) in edges} | {"commit", "stutter"})
    lines = []
    lines.append(f"// sb_{model}.ctxdsl — store-buffering litmus, {model.upper()} memory model.")
    lines.append("// Generated by generate.py — explicit-state operational model.")
    lines.append(f"context Sb{model.upper()} {{")
    lines.append("    automata {")
    lines.append(f"        automaton Sb{model.upper()} {{")
    lines.append("            controllable {")
    for lbl in labels:
        lines.append(f"                label {lbl};")
    lines.append("            }")
    lines.append("            states {")
    lines.append(f"                state {name(INIT)} initial;")
    for s in sorted(seen, key=name):
        if s == INIT:
            continue
        lines.append(f"                state {name(s)};")
    lines.append("                state BothReadZero;")
    lines.append("                state OtherOutcome;")
    lines.append("            }")
    lines.append("            transitions {")
    for (s, lbl, t) in edges:
        lines.append(f"                transition {name(s)} -> {name(t)} on label {lbl};")
    for (s, outcome) in commits:
        lines.append(f"                transition {name(s)} -> {outcome} on label commit;")
    # Absorbing self-loops so the outcome states are not deadlocks.
    lines.append("                transition BothReadZero -> BothReadZero on label stutter;")
    lines.append("                transition OtherOutcome -> OtherOutcome on label stutter;")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_verify_toml(model):
    reachable_expected = "true (the TSO relaxation is observable)" if model == "tso" \
        else "false (SC / the fence forbids r0=r1=0)"
    cls = model.upper()
    lines = []
    lines.append(f"# v2_tso_storebuffer / {model} — V.2 of the §Phase 7 domain-validation track.")
    lines.append("# Controlling doc: docs/design/industrial-value-and-validation-domains.md §5")
    lines.append("# (memory consistency). GENERATED by ../generate.py — do not hand-edit.")
    lines.append("#")
    lines.append("# Store-buffering litmus (Thread0: x=1; r0=y  ||  Thread1: y=1; r1=x).")
    lines.append(f"# Memory model: {cls}. Discriminating verdict:")
    lines.append(f"#   both_read_zero_reachable = {reachable_expected}")
    lines.append("# This is the canonical SB result (herd / rmem / any MCM textbook).")
    lines.append("")
    lines.append("[project]")
    lines.append(f'name = "V2_SB_{cls}"')
    lines.append(f'description = "V.2 store-buffering litmus, {cls} memory model. r0=r1=0 reachable iff the model relaxes write→read order."')
    lines.append("")
    lines.append("[[sources]]")
    lines.append(f'id = "Sb{cls}"')
    lines.append('adapter = "ctxdsl"')
    lines.append(f'files = ["sb_{model}.ctxdsl"]')
    lines.append("")
    lines.append("[alphabet]")
    lines.append('strategy = "direct"')
    lines.append("")
    lines.append("[composition]")
    lines.append('semantics = "asynchronous"')
    lines.append(f'members = ["Sb{cls}"]')
    lines.append('name = "SbSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# The litmus check: is the both-read-zero outcome observable?")
    lines.append('name = "both_read_zero_reachable"')
    lines.append('template = "reachable"')
    lines.append('args = { TARGET = "BothReadZero" }')
    lines.append('over = "SbSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Sanity: some non-both-zero outcome is always observable (both models).")
    lines.append('name = "other_outcome_reachable"')
    lines.append('template = "reachable"')
    lines.append('args = { TARGET = "OtherOutcome" }')
    lines.append('over = "SbSystem"')
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in ("tso", "sc"):
        print("usage: generate.py <tso|sc> <out_dir>", file=sys.stderr)
        sys.exit(2)
    model, out = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    seen, edges, commits = generate(model)
    with open(os.path.join(out, f"sb_{model}.ctxdsl"), "w") as f:
        f.write(emit_ctxdsl(model, seen, edges, commits))
    with open(os.path.join(out, "verify.toml"), "w") as f:
        f.write(emit_verify_toml(model))
    both = any(o == "BothReadZero" for (_s, o) in commits)
    print(f"generated {model}: {len(seen)} states, {len(edges)} edges, "
          f"BothReadZero {'reachable' if both else 'UNreachable'} in the operational model")


if __name__ == "__main__":
    main()
