#!/usr/bin/env python3
"""V.1 4-router NoC liveness generator — §Phase 7 domain-validation track.

    generate.py <progress|contention> <out_dir>

Emits a CTXDSL model of a single flit traversing a 2x2 mesh NoC (4 routers)
from the R0 corner to the diagonally-opposite R3 corner, plus a verify.toml,
for one scheduling discipline:

  R0 --- R1          A flit injected at R0, destined R3. Adaptive minimal
  |      |           routing: at R0 it may take either column (R0->R1->R3 or
  R2 --- R3          R0->R2->R3); both are diameter-length (2 hops).

  - **progress**  : every router forwards on the next step (a fair / always-
    making-progress scheduler). No router ever stalls.
  - **contention**: every intermediate router MAY stall (`wait_r*` self-loop),
    modelling an unfair scheduler where another flow's traffic holds the
    output port indefinitely. The flit can dawdle for unboundedly many time
    steps — but a stall is NOT a hop, so the *hop* count is unaffected.

A `hops` counter variable increments on each forward and is the "counter
valuation" the V.1 done-criterion calls for. Because the realize/unroll path
binds `hops == k` / `hops <= k` atoms (the 2026-06-23 CTXDSL variable-atom
binding fix), bounded delivery is expressed directly over the counter rather
than encoded into state names.

Properties (verify.toml):
  deadlock_freedom     safety  : every reachable state has an enabled
                                 transition. Non-vacuous — the absorbing
                                 delivered state R3 needs its stutter
                                 self-loop; drop it and R3 deadlocks.
  liveness_possible    nu/mu   : AG EF delivered ("always eventually" template,
                                 a nu-mu depth-2 alternation). From every
                                 reachable state, delivery REMAINS reachable
                                 (no deadlock/livelock trap). TRUE in both
                                 disciplines.
  liveness_inevitable  mu (AF) : on EVERY path the flit is eventually delivered
                                 (strong inevitability). TRUE under `progress`;
                                 FALSE under `contention` — without a fairness
                                 constraint the all-stall path never delivers.
                                 This is the discriminating verdict, and it is
                                 the honest fairness boundary (CLAUDE.md
                                 Soundness Guarantees: a liveness verdict needs
                                 fairness; mununu imposes none on the stall).
  hop_bound            safety  : `hops <= 2` invariant — delivery never exceeds
                                 the mesh diameter (2 hops). TRUE in both: a
                                 stall adds latency, not hops.
  delivered_at_diameter mu     : a delivered state with exactly `hops == 2` is
                                 reachable. TRUE in both. Exercises the counter
                                 binding on the reachability (mu) path.

This is a generated design-pattern demonstration of the NoC-liveness domain,
NOT a finding about a real interconnect (claims-integrity). The single-flit
abstract `wait` over-approximates contention from other flows; the liveness
verdicts are reported under exactly that reading.
"""
import sys
import os

ROUTERS = ["R0", "R1", "R2", "R3"]
# Adaptive minimal-routing forward edges for a flit R0 -> R3 in the 2x2 mesh.
FORWARD = [
    ("R0", "R1", "fwd_r0_r1"),
    ("R0", "R2", "fwd_r0_r2"),
    ("R1", "R3", "fwd_r1_r3"),
    ("R2", "R3", "fwd_r2_r3"),
]
# Routers that can stall under contention (everything but the destination).
STALLERS = ["R0", "R1", "R2"]


def emit_ctxdsl(model):
    stalls = model == "contention"
    labels = [lbl for (_s, _t, lbl) in FORWARD] + ["deliver_stutter"]
    if stalls:
        labels += [f"wait_{r.lower()}" for r in STALLERS]

    lines = []
    lines.append(f"// noc_{model}.ctxdsl — single flit through a 2x2 mesh NoC, {model} scheduler.")
    lines.append("// Generated by generate.py — do not hand-edit; re-run the generator.")
    lines.append("context Noc {")
    lines.append("    automata {")
    lines.append("        automaton Noc {")
    lines.append("            controllable {")
    for lbl in labels:
        lines.append(f"                label {lbl};")
    lines.append("            }")
    lines.append("            variables { var hops : i64 = 0; }")
    lines.append("            states {")
    lines.append("                state R0 initial;")
    for r in ROUTERS[1:]:
        lines.append(f"                state {r};")
    lines.append("            }")
    lines.append("            transitions {")
    if stalls:
        for r in STALLERS:
            lines.append(f"                transition {r} -> {r} on label wait_{r.lower()};")
    for (s, t, lbl) in FORWARD:
        lines.append(f"                transition {s} -> {t} on label {lbl} effects {{ hops = hops + 1; }};")
    lines.append("                transition R3 -> R3 on label deliver_stutter;")
    lines.append("            }")
    lines.append("            predicates { predicate delivered = state R3; }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_verify_toml(model):
    inevitable = "true (fair scheduler ⇒ every path delivers)" if model == "progress" \
        else "false (an unfair all-stall path never delivers)"
    lines = []
    lines.append(f"# v1_noc_mesh_4router / {model} — V.1 of the §Phase 7 domain-validation track.")
    lines.append("# Controlling doc: docs/design/industrial-value-and-validation-domains.md §4 (NoC")
    lines.append("# liveness). GENERATED by ../generate.py — do not hand-edit.")
    lines.append("#")
    lines.append("# Single flit R0 -> R3 across a 2x2 mesh. Discriminating verdict:")
    lines.append(f"#   liveness_inevitable = {inevitable}")
    lines.append("# liveness_possible (AG EF) + deadlock_freedom + hop_bound + delivered_at_diameter")
    lines.append("# hold in BOTH disciplines. Sharp-everywhere explicit model; definite 2-valued")
    lines.append("# verdicts directly. The `hops` counter binds via the CTXDSL variable-atom path.")
    lines.append("")
    lines.append("[project]")
    cls = model.capitalize()
    lines.append(f'name = "V1_NoC_{cls}"')
    lines.append(f'description = "V.1 4-router NoC liveness, {model} scheduler. Deadlock-freedom + end-to-end liveness (possibility always; inevitability only under a fair scheduler) + bounded (<= diameter) delivery over a hop counter."')
    lines.append("")
    lines.append("[[sources]]")
    lines.append('id = "Noc"')
    lines.append('adapter = "ctxdsl"')
    lines.append(f'files = ["noc_{model}.ctxdsl"]')
    lines.append("")
    lines.append("[alphabet]")
    lines.append('strategy = "direct"')
    lines.append("")
    lines.append("[composition]")
    lines.append('semantics = "asynchronous"')
    lines.append('members = ["Noc"]')
    lines.append('name = "NocSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Every reachable state has an enabled transition (R3's stutter keeps it live).")
    lines.append('name = "deadlock_freedom"')
    lines.append('template = "no_deadlock"')
    lines.append('over = "NocSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# AG EF delivered: delivery REMAINS reachable from every reachable state.")
    lines.append('name = "liveness_possible"')
    lines.append('template = "always_eventually"')
    lines.append('args = { TARGET = "delivered" }')
    lines.append('over = "NocSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# AF delivered: on EVERY path the flit is eventually delivered (inevitability).")
    lines.append("# TRUE under progress; FALSE under contention (the unfair stall path starves it).")
    lines.append('name = "liveness_inevitable"')
    lines.append('formula = "mu X. (delivered || ([] X && <> true))"')
    lines.append('over = "NocSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Bounded delivery (safety over the counter): hops never exceeds the diameter.")
    lines.append('name = "hop_bound"')
    lines.append('formula = "nu X. (hops <= 2 && [] X)"')
    lines.append('over = "NocSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Bounded delivery (reachability over the counter): delivered at exactly 2 hops.")
    lines.append('name = "delivered_at_diameter"')
    lines.append('formula = "mu X. ((delivered && hops == 2) || <> X)"')
    lines.append('over = "NocSystem"')
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in ("progress", "contention"):
        print("usage: generate.py <progress|contention> <out_dir>", file=sys.stderr)
        sys.exit(2)
    model, out = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, f"noc_{model}.ctxdsl"), "w") as f:
        f.write(emit_ctxdsl(model))
    with open(os.path.join(out, "verify.toml"), "w") as f:
        f.write(emit_verify_toml(model))
    print(f"generated {model} into {out} (noc_{model}.ctxdsl + verify.toml)")


if __name__ == "__main__":
    main()
