#!/usr/bin/env python3
"""gen_gr1.py — Generate scalable GR(1) CTXDSL benchmarks for Mununu.

Generates hub-and-spoke automata with n request/grant pairs and k noise states:
  - Total states:    2n + k + 1
  - Labels:          3n + 1  (req_i, grant_i, done_i per pair + tick)
  - Formula:         ∧_{i=0}^{n-1} (□◇ Req_i → □◇ Grant_i)
  - Controllable:    grant_0 .. grant_{n-1}
  - Uncontrollable:  req_0 .. req_{n-1}, done_0 .. done_{n-1}, tick

The property is always realizable: from any Req_i state, the controller
immediately grants via grant_i — no competing obligations can block it.

Usage:
    # Single file
    python3 gen_gr1.py --pairs 3 --noise 10 --output out.ctxdsl

    # Formula scaling batch: n=1..10, k=0  → gr1_n01_s003.ctxdsl ..
    python3 gen_gr1.py --formula-scale [--outdir DIR]

    # State scaling batch: n=2, k=7,98,...,49998  → gr1_n02_s000012.ctxdsl ..
    python3 gen_gr1.py --state-scale [--outdir DIR]

    # Both batches
    python3 gen_gr1.py --all [--outdir DIR]
"""

import argparse
import os
import sys
import textwrap


# ── CTXDSL generation ─────────────────────────────────────────────────────────

def gen_context(n: int, k: int) -> str:
    """Return a complete CTXDSL context string for n pairs and k noise states."""
    total_states = 2 * n + k + 1
    context_name = f"gr1_n{n:02d}_s{total_states:07d}"
    lines: list[str] = []

    # ── Header comment ──────────────────────────────────────────────────────
    lines += [
        f"// Scalable GR(1) benchmark — {n} conjunct(s), {total_states} states",
        f"//   Property: ∧_{{i=0}}^{{{n-1}}} (□◇ Req_i → □◇ Grant_i)",
        f"//   States:   Hub + {n}×(Req_i, Grant_i) + {k} Noise states",
        f"//   Generated by examples/scalable/gen_gr1.py",
        f"//   Run: mununu context eval FILE --formula gr1_liveness --automaton Scheduler",
        "",
        f"context {context_name} {{",
    ]

    # ── Alphabet ────────────────────────────────────────────────────────────
    lines.append("    alphabet {")
    for i in range(n):
        lines.append(f"        label req_{i};")
        lines.append(f"        label grant_{i};")
        lines.append(f"        label done_{i};")
    if k > 0:
        lines.append("        label tick;")
    lines.append("    }")
    lines.append("")

    # ── Automata ────────────────────────────────────────────────────────────
    lines.append("    automata {")
    lines.append("        automaton Scheduler {")

    # Controllable labels
    lines.append("            controllable {")
    for i in range(n):
        lines.append(f"                label grant_{i};")
    lines.append("            }")

    # States
    lines.append("            states {")
    lines.append("                state Hub initial;")
    for i in range(n):
        lines.append(f"                state Req{i};")
        lines.append(f"                state Grant{i};")
    for j in range(k):
        lines.append(f"                state Noise{j};")
    lines.append("            }")

    # Transitions
    lines.append("            transitions {")
    for i in range(n):
        lines.append(f"                transition Hub -> Req{i} on label req_{i};")
        lines.append(f"                transition Req{i} -> Grant{i} on label grant_{i};")
        lines.append(f"                transition Grant{i} -> Hub on label done_{i};")
    # Star topology: Hub <-> each Noise_j directly on tick.
    # Each noise state has exactly 2 transitions (in and out), giving O(1)
    # fixpoint depth regardless of k (vs O(k) for a ring).
    if k > 0:
        for j in range(k):
            lines.append(f"                transition Hub -> Noise{j} on label tick;")
            lines.append(f"                transition Noise{j} -> Hub on label tick;")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # ── Formula ─────────────────────────────────────────────────────────────
    # ∧_{i=0}^{n-1} (¬GF(Req_i) ∨ GF(Grant_i))
    # GF(S) = nu NuS. (mu MuS. (S || <> MuS)) && ([] NuS)
    # ¬GF(S) = ! (nu NuS. (mu MuS. (S || <> MuS)) && ([] NuS))
    lines.append("    mu_formulas {")
    lines.append("        formula gr1_liveness {")
    lines.append("            over Scheduler;")

    pair_exprs: list[str] = []
    for i in range(n):
        not_gf_req = (
            f"(! (nu NuA{i}. (mu MuA{i}. (Req{i} || <> MuA{i})) && ([] NuA{i})))"
        )
        gf_grant = (
            f"(nu NuG{i}. (mu MuG{i}. (Grant{i} || <> MuG{i})) && ([] NuG{i}))"
        )
        pair_exprs.append(f"({not_gf_req}\n                    || {gf_grant})")

    if n == 1:
        body = pair_exprs[0]
    else:
        body = "\n                    && ".join(pair_exprs)

    lines.append(f"            body = {body};")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # ── Controller ──────────────────────────────────────────────────────────
    lines.append("    controllers {")
    lines.append("        controller fair_scheduler {")
    lines.append("            source Scheduler;")
    lines.append("            satisfying gr1_liveness;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines) + "\n"


# ── Batch helpers ─────────────────────────────────────────────────────────────

def formula_scale_params():
    """n=1..10, k=0 → each file has 2n+1 states."""
    return [(n, 0) for n in range(1, 11)]


def state_scale_params():
    """n=2, k ∈ {7, 98, 998, 9998, 49998} → states ∈ {12, 103, 1003, 10003, 50003}."""
    # k = target_states - 2n - 1 = target_states - 5
    targets = [12, 103, 1_003, 10_003, 50_003]
    n = 2
    return [(n, t - 2 * n - 1) for t in targets]


def filename(n: int, k: int) -> str:
    total = 2 * n + k + 1
    return f"gr1_n{n:02d}_s{total:07d}.ctxdsl"


def write_file(n: int, k: int, outdir: str) -> str:
    os.makedirs(outdir, exist_ok=True)
    fname = os.path.join(outdir, filename(n, k))
    with open(fname, "w") as f:
        f.write(gen_context(n, k))
    return fname


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description=textwrap.dedent(__doc__),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--pairs", "-n", type=int, help="Number of GR(1) pairs")
    parser.add_argument("--noise", "-k", type=int, default=0,
                        help="Number of noise ring states (default: 0)")
    parser.add_argument("--output", "-o", metavar="FILE",
                        help="Output file (default: stdout)")
    parser.add_argument("--formula-scale", action="store_true",
                        help="Generate formula-scaling batch (n=1..10, k=0)")
    parser.add_argument("--state-scale", action="store_true",
                        help="Generate state-scaling batch (n=2, k=7..49998)")
    parser.add_argument("--all", dest="all_batches", action="store_true",
                        help="Generate both scaling batches")
    parser.add_argument("--outdir", default=".",
                        help="Output directory for batch mode (default: .)")
    args = parser.parse_args()

    # Batch modes
    if args.all_batches or args.formula_scale or args.state_scale:
        params: list[tuple[int, int]] = []
        if args.all_batches or args.formula_scale:
            params += formula_scale_params()
        if args.all_batches or args.state_scale:
            params += state_scale_params()

        # Deduplicate while preserving order
        seen: set[tuple[int, int]] = set()
        unique_params = []
        for p in params:
            if p not in seen:
                seen.add(p)
                unique_params.append(p)

        for n, k in unique_params:
            fname = write_file(n, k, args.outdir)
            total = 2 * n + k + 1
            print(f"  wrote {fname}  ({n} pairs, {total} states)", file=sys.stderr)
        return

    # Single-file mode
    if args.pairs is None:
        parser.error("--pairs is required in single-file mode (or use --formula-scale / --state-scale)")

    content = gen_context(args.pairs, args.noise)
    if args.output:
        with open(args.output, "w") as f:
            f.write(content)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(content)


if __name__ == "__main__":
    main()
