#!/usr/bin/env python3
"""V.4 parametric MESI generator — §Phase 7 domain-validation track.

Emits an N-agent MESI cache-coherence verification project (N L1 caches
over one tracked line + a shared memory) into a target directory:

    generate.py <N> <out_dir>

This script IS the "parametric template" the V.4 done-criterion calls for;
the checked-in n2/ n4/ n8/ directories are its instantiations. The model
is hand-authored / generated — a design-pattern demonstration of the
cache-coherence domain, NOT a finding about a real silicon protocol
(claims-integrity).

Protocol (MSI/MESI, single tracked line):
  - Local read  `xact_read_x_core{K}`  : C{K}  I->E, others idempotent.
  - Local write `xact_write_x_core{K}` : C{K}  *->M; ALL OTHER caches snoop
    the write and invalidate (*->I). Async rendezvous on the shared label
    makes the write + the broadcast invalidation atomic, so AT MOST ONE
    cache is ever in M (the coherence invariant).
  - Snoop read `xact_read_x_core{J}` (J!=K): C{K} E/M -> S (downgrade).
  - Memory transitions Mem_Initial -> Mem_Written on any write (the
    write becomes visible), idempotent on reads.

Cache 0 owns every bus label in its `controllable` block (the V.0
convention); caches 1..N-1 and the memory reference them without
re-declaring, so the realiser does not infer duplicate controllability.
"""
import sys
import os


def cache_ctxdsl(k, n):
    labels = []
    for j in range(n):
        labels.append(f"xact_read_x_core{j}")
        labels.append(f"xact_write_x_core{j}")

    lines = []
    lines.append(f"// cache_{k}.ctxdsl — Core {k}'s L1 cache (V.4 parametric MESI, N={n}).")
    lines.append("// Generated by generate.py — do not hand-edit; re-run the generator.")
    lines.append(f"context C{k} {{")
    lines.append("    automata {")
    lines.append(f"        automaton C{k} {{")
    if k == 0:
        # Cache 0 owns all bus labels (V.0 convention).
        lines.append("            controllable {")
        for lbl in labels:
            lines.append(f"                label {lbl};")
        lines.append("            }")
    lines.append("            states {")
    lines.append(f"                state C{k}_I initial;")
    lines.append(f"                state C{k}_S;")
    lines.append(f"                state C{k}_E;")
    lines.append(f"                state C{k}_M;")
    lines.append("            }")
    lines.append("            transitions {")
    # Local read.
    lines.append(f"                transition C{k}_I -> C{k}_E on label xact_read_x_core{k};")
    lines.append(f"                transition C{k}_S -> C{k}_S on label xact_read_x_core{k};")
    lines.append(f"                transition C{k}_E -> C{k}_E on label xact_read_x_core{k};")
    lines.append(f"                transition C{k}_M -> C{k}_M on label xact_read_x_core{k};")
    # Local write: * -> M.
    for s in ("I", "S", "E", "M"):
        lines.append(f"                transition C{k}_{s} -> C{k}_M on label xact_write_x_core{k};")
    # Snoops of every other core.
    for j in range(n):
        if j == k:
            continue
        # Snoop write: invalidate.
        for s in ("I", "S", "E", "M"):
            lines.append(f"                transition C{k}_{s} -> C{k}_I on label xact_write_x_core{j};")
        # Snoop read: downgrade E/M -> S, I/S idempotent.
        lines.append(f"                transition C{k}_I -> C{k}_I on label xact_read_x_core{j};")
        lines.append(f"                transition C{k}_S -> C{k}_S on label xact_read_x_core{j};")
        lines.append(f"                transition C{k}_E -> C{k}_S on label xact_read_x_core{j};")
        lines.append(f"                transition C{k}_M -> C{k}_S on label xact_read_x_core{j};")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def memory_ctxdsl(n):
    lines = []
    lines.append(f"// memory.ctxdsl — shared memory for the V.4 parametric MESI (N={n}).")
    lines.append("// Generated by generate.py. Mem_Initial -> Mem_Written on any write")
    lines.append("// (the write becomes visible); idempotent on reads.")
    lines.append("context Memory {")
    lines.append("    automata {")
    lines.append("        automaton Memory {")
    lines.append("            states {")
    lines.append("                state Mem_Initial initial;")
    lines.append("                state Mem_Written;")
    lines.append("            }")
    lines.append("            transitions {")
    for k in range(n):
        lines.append(f"                transition Mem_Initial -> Mem_Written on label xact_write_x_core{k};")
        lines.append(f"                transition Mem_Written -> Mem_Written on label xact_write_x_core{k};")
        lines.append(f"                transition Mem_Initial -> Mem_Initial on label xact_read_x_core{k};")
        lines.append(f"                transition Mem_Written -> Mem_Written on label xact_read_x_core{k};")
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def verify_toml(n):
    members = ", ".join([f'"C{k}"' for k in range(n)] + ['"Memory"'])
    # N-way coherence safety: at most one cache in M ⇒ no two simultaneously.
    pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            pairs.append(f"!(C{i}_M && C{j}_M)")
    safety_formula = "nu X. (" + " && ".join(pairs) + " && [] X)"

    lines = []
    lines.append(f"# v4_mesi_parametric / n{n} — V.4 of the §Phase 7 domain-validation track.")
    lines.append("# Controlling doc: docs/design/industrial-value-and-validation-domains.md §3")
    lines.append("# (parameterised cache coherence). GENERATED by ../generate.py — do not")
    lines.append(f"# hand-edit. {n} L1 caches over one tracked line + shared memory, free")
    lines.append("# environment driving. Sharp-everywhere (explicit async composition);")
    lines.append("# definite 2-valued verdicts directly — no CEGAR / KleeneBot needed at")
    lines.append("# this scale (stronger than the plan's 'CEGAR converge' criterion).")
    lines.append("#")
    lines.append("# Properties (all must be `true`):")
    lines.append("#   - coherence_safety   : at most one cache in M (the coherence invariant)")
    lines.append("#   - deadlock_freedom   : every reachable state has an enabled transition")
    lines.append("#   - write_visibility   : a write is always eventually visible in memory")
    lines.append("#                          (nu/mu alternation — the liveness shape)")
    lines.append("")
    lines.append("[project]")
    lines.append(f'name = "V4_MESI_N{n}"')
    lines.append(f'description = "V.4 parametric MESI — {n} L1 caches + shared memory. Coherence safety + deadlock-freedom + eventual write visibility."')
    lines.append("")
    for k in range(n):
        lines.append("[[sources]]")
        lines.append(f'id = "C{k}"')
        lines.append('adapter = "ctxdsl"')
        lines.append(f'files = ["cache_{k}.ctxdsl"]')
        lines.append("")
    lines.append("[[sources]]")
    lines.append('id = "Memory"')
    lines.append('adapter = "ctxdsl"')
    lines.append('files = ["memory.ctxdsl"]')
    lines.append("")
    lines.append("[alphabet]")
    lines.append('strategy = "direct"')
    lines.append("")
    lines.append("[composition]")
    lines.append('semantics = "asynchronous"')
    lines.append(f"members = [{members}]")
    lines.append('name = "MesiSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# At most one cache in Modified ⇒ no two M copies (C(N,2) pairwise terms).")
    lines.append('name = "coherence_safety"')
    lines.append(f'formula = "{safety_formula}"')
    lines.append('over = "MesiSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append('name = "deadlock_freedom"')
    lines.append('template = "no_deadlock"')
    lines.append('over = "MesiSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Eventual write visibility (nu Y. (mu X. (Mem_Written || <> X)) && [] Y).")
    lines.append('name = "write_visibility"')
    lines.append('template = "always_eventually"')
    lines.append('args = { TARGET = "Mem_Written" }')
    lines.append('over = "MesiSystem"')
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        print("usage: generate.py <N> <out_dir>", file=sys.stderr)
        sys.exit(2)
    n = int(sys.argv[1])
    out = sys.argv[2]
    os.makedirs(out, exist_ok=True)
    for k in range(n):
        with open(os.path.join(out, f"cache_{k}.ctxdsl"), "w") as f:
            f.write(cache_ctxdsl(k, n))
    with open(os.path.join(out, "memory.ctxdsl"), "w") as f:
        f.write(memory_ctxdsl(n))
    with open(os.path.join(out, "verify.toml"), "w") as f:
        f.write(verify_toml(n))
    print(f"generated N={n} into {out} ({n} caches + memory + verify.toml)")


if __name__ == "__main__":
    main()
