#!/usr/bin/env python3
"""V.3 speculative non-interference generator — §Phase 7 domain-validation track.

    generate.py <vulnerable|safe> <out_dir>

Emits a CTXDSL model of the **self-composition** of a speculative-load side
channel, plus a verify.toml, for one design:

  A victim speculatively executes an out-of-bounds load (Spectre-v1 essence):
  the branch is predicted taken, a secret byte is read under misspeculation,
  and the secret-dependent address touches a cache line BEFORE the
  misprediction resolves. The cache footprint is the attacker-**observable**.

Non-interference is a 2-safety hyperproperty: two runs that agree on every
**public** input must agree on every observation, regardless of the **secret**.
We check it by SELF-COMPOSITION — two copies (A, B) of the victim run with the
same public input (both speculate the same access) but **independent secret
values**; a final `observe` compares their cache footprints. The 2-safety
hyperproperty reduces to ordinary safety on the product: `never(Leak)`, where
`Leak` is the product state in which the two cache footprints differ.

Two designs:
  - **vulnerable** : the speculative load touches `cache[secret]`, so each copy's
    footprint is its secret (∈ {0,1}). When secretA ≠ secretB the footprints
    differ ⇒ `Leak` reachable ⇒ non-interference FAILS.
  - **safe**       : the speculative load is squashed before it can update the
    cache (the mitigation — speculation leaves no architectural-or-cache trace),
    so every copy's footprint is `none` regardless of secret ⇒ only `Agree`
    reachable ⇒ non-interference HOLDS.

So `never(Leak)` is the discriminating contract-conformance verdict:
  safe ⇒ true   (the speculation contract "no secret-dependent cache trace"
                 is met), vulnerable ⇒ false.
Its dual `reachable(Leak)` is the non-vacuity witness (true iff the leak exists).

The model is a generated **design-pattern demonstration** of the speculative-
non-interference domain — an abstract model of the speculation→cache side
channel, NOT an RTL pipeline and NOT a production Spectre checker (research-
grade per the value-proposition doc §6; claims-integrity). The pipeline,
branch predictor, and cache are abstracted to the load-bearing behaviour: a
speculative load whose cache footprint does (vulnerable) or does not (safe)
depend on the secret.
"""
import sys
import os
from collections import deque

INIT = ("S", "S")  # (copyA footprint-or-Start, copyB footprint-or-Start)


def outcomes(model):
    # The resolved cache footprints a single copy can reach from Start.
    if model == "vulnerable":
        return ["0", "1"]   # speculative load touches cache[secret]; secret ∈ {0,1}
    return ["n"]            # safe: squashed ⇒ no secret-dependent cache update


def name(s):
    a, b = s
    return f"A{a}_B{b}"


def generate(model):
    outs = outcomes(model)
    seen = {INIT}
    edges = []          # (src, label, dst)
    observes = []       # (both-resolved src, "Agree"|"Leak")
    q = deque([INIT])
    while q:
        a, b = s = q.popleft()
        if a != "S" and b != "S":
            observes.append((s, "Agree" if a == b else "Leak"))
            continue
        succ = []
        if a == "S":
            for o in outs:
                succ.append((f"resolveA_{o}", (o, b)))
        if b == "S":
            for o in outs:
                succ.append((f"resolveB_{o}", (a, o)))
        for lbl, t in succ:
            edges.append((s, lbl, t))
            if t not in seen:
                seen.add(t)
                q.append(t)
    return seen, edges, observes


def emit_ctxdsl(model, seen, edges, observes):
    labels = sorted({lbl for (_s, lbl, _t) in edges} | {"observe", "stutter"})
    lines = []
    lines.append(f"// spec_{model}.ctxdsl — self-composed speculative-load side channel, {model}.")
    lines.append("// Generated by generate.py — do not hand-edit; re-run the generator.")
    lines.append("// State = (copyA cache footprint, copyB cache footprint); S = pre-resolution.")
    lines.append("context Spec {")
    lines.append("    automata {")
    lines.append("        automaton Spec {")
    lines.append("            controllable {")
    for lbl in labels:
        lines.append(f"                label {lbl};")
    lines.append("            }")
    lines.append("            states {")
    lines.append(f"                state {name(INIT)} initial;")
    for s in sorted(seen, key=name):
        if s == INIT:
            continue
        lines.append(f"                state {name(s)};")
    lines.append("                state Agree;")
    lines.append("                state Leak;")
    lines.append("            }")
    lines.append("            transitions {")
    for (s, lbl, t) in edges:
        lines.append(f"                transition {name(s)} -> {name(t)} on label {lbl};")
    for (s, outcome) in observes:
        lines.append(f"                transition {name(s)} -> {outcome} on label observe;")
    lines.append("                transition Agree -> Agree on label stutter;")
    lines.append("                transition Leak -> Leak on label stutter;")
    lines.append("            }")
    lines.append("            predicates { predicate leak = state Leak; predicate agree = state Agree; }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_verify_toml(model):
    ni = "true (the no-secret-dependent-cache-trace contract holds)" if model == "safe" \
        else "false (a secret-dependent cache trace leaks under misspeculation)"
    cls = model.capitalize()
    lines = []
    lines.append(f"# v3_specsafe_pipeline / {model} — V.3 of the §Phase 7 domain-validation track.")
    lines.append("# Controlling doc: docs/design/industrial-value-and-validation-domains.md §6")
    lines.append("# (speculative-execution security / hyperproperties). GENERATED by ../generate.py")
    lines.append("# — do not hand-edit.")
    lines.append("#")
    lines.append("# Self-composition of a speculative-load side channel. Discriminating verdict:")
    lines.append(f"#   noninterference = {ni}")
    lines.append("# Non-interference (a 2-safety hyperproperty) reduces to safety on the self-")
    lines.append("# composed product: never(Leak), where Leak = the two copies' cache footprints")
    lines.append("# differ under equal public input + differing secret. Research-grade abstract")
    lines.append("# model (claims-integrity), NOT a production Spectre checker.")
    lines.append("")
    lines.append("[project]")
    lines.append(f'name = "V3_SpecSafe_{cls}"')
    lines.append(f'description = "V.3 speculative non-interference, {model} design. Self-composed speculative-load side channel; never(Leak) is the contract-conformance verdict."')
    lines.append("")
    lines.append("[[sources]]")
    lines.append('id = "Spec"')
    lines.append('adapter = "ctxdsl"')
    lines.append(f'files = ["spec_{model}.ctxdsl"]')
    lines.append("")
    lines.append("[alphabet]")
    lines.append('strategy = "direct"')
    lines.append("")
    lines.append("[composition]")
    lines.append('semantics = "asynchronous"')
    lines.append('members = ["Spec"]')
    lines.append('name = "SpecSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Non-interference / contract conformance: the two copies' observable cache")
    lines.append("# footprints never disagree ⇒ no secret-dependent cache trace.")
    lines.append('name = "noninterference"')
    lines.append('template = "never"')
    lines.append('args = { BAD = "Leak" }')
    lines.append('over = "SpecSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Non-vacuity witness (dual of noninterference): the leak IS observable.")
    lines.append('name = "leak_reachable"')
    lines.append('template = "reachable"')
    lines.append('args = { TARGET = "Leak" }')
    lines.append('over = "SpecSystem"')
    lines.append("")
    lines.append("[[properties]]")
    lines.append("# Sanity: every reachable product state has an enabled transition.")
    lines.append('name = "deadlock_freedom"')
    lines.append('template = "no_deadlock"')
    lines.append('over = "SpecSystem"')
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in ("vulnerable", "safe"):
        print("usage: generate.py <vulnerable|safe> <out_dir>", file=sys.stderr)
        sys.exit(2)
    model, out = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    seen, edges, observes = generate(model)
    with open(os.path.join(out, f"spec_{model}.ctxdsl"), "w") as f:
        f.write(emit_ctxdsl(model, seen, edges, observes))
    with open(os.path.join(out, "verify.toml"), "w") as f:
        f.write(emit_verify_toml(model))
    leak = any(o == "Leak" for (_s, o) in observes)
    print(f"generated {model}: {len(seen)} product states, {len(edges)} edges, "
          f"Leak {'reachable' if leak else 'UNreachable'}")


if __name__ == "__main__":
    main()
