//! Emit a synthesized controller CLTS as a SystemVerilog module.
//!
//! Produces a `module` with `typedef enum`, `always_ff`, and `case` statement
//! that implements the synthesized strategy. Optionally preserves the original
//! module's port interface.

use crate::clts::{Clts, DefaultLabelIdx, DefaultStateIdx};
use std::fmt::Write;

/// Port definition for the emitted controller module.
#[derive(Debug, Clone)]
pub struct SvPort {
    pub name: String,
    pub direction: &'static str, // "input" or "output"
    pub width: usize,            // 1 = single bit
}

/// Sanitize a controller state name into a legal SystemVerilog identifier. Composite
/// product-state names (e.g. `Free|Idle|Idle`) carry `|` and other non-identifier
/// characters that are illegal as `enum` literals — the emitted module would not
/// compile. Map every non-`[A-Za-z0-9_]` character to `_`, prefix a leading digit, and
/// never emit the empty string. (Two distinct states that differ only in punctuation
/// could collide; product-state names use consistent separators, so this is safe in
/// practice — a future revision can index-suffix on collision.)
fn sv_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() {
        return "s_empty".to_string();
    }
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s = format!("s_{s}");
    }
    s
}

/// Convert a synthesized controller CLTS to a SystemVerilog module string.
///
/// If `ports` is provided, the module declaration preserves the original
/// port interface. Otherwise, only `clk` and `rst` are emitted.
pub fn controller_to_systemverilog(
    controller: &Clts<DefaultStateIdx, DefaultLabelIdx>,
    module_name: &str,
    realizable: bool,
) -> String {
    controller_to_systemverilog_with_ports(controller, module_name, realizable, &[])
}

/// Convert a synthesized controller CLTS to a SystemVerilog module with
/// the original port interface preserved.
pub fn controller_to_systemverilog_with_ports(
    controller: &Clts<DefaultStateIdx, DefaultLabelIdx>,
    module_name: &str,
    realizable: bool,
    ports: &[SvPort],
) -> String {
    let mut out = String::with_capacity(2048);

    writeln!(
        out,
        "// Generated by Mununu — correct-by-construction controller"
    )
    .unwrap();
    writeln!(
        out,
        "// Synthesis result: {}",
        if realizable {
            "realizable"
        } else {
            "unrealizable"
        }
    )
    .unwrap();
    writeln!(out).unwrap();

    if !realizable || controller.state_count() == 0 {
        writeln!(
            out,
            "// No controller generated (unrealizable specification)"
        )
        .unwrap();
        return out;
    }

    // Collect state names and initial state
    let mut state_names: Vec<String> = Vec::new();
    let mut initial_name = String::new();
    let initials = controller.initial_states();

    for state_id in controller.states() {
        let name = sv_ident(controller.state_name(state_id).unwrap_or("unknown"));
        if initials.contains(&state_id) && initial_name.is_empty() {
            initial_name = name.clone();
        }
        state_names.push(name);
    }

    // Calculate enum width
    let width = if state_names.len() <= 2 {
        1
    } else {
        (state_names.len() as f64).log2().ceil() as usize
    };

    // Module declaration with ports
    writeln!(out, "module {module_name}_controller (").unwrap();
    if ports.is_empty() {
        writeln!(out, "    input  logic clk,").unwrap();
        writeln!(out, "    input  logic rst").unwrap();
    } else {
        let port_lines: Vec<String> = ports
            .iter()
            .map(|p| {
                if p.width > 1 {
                    format!("    {}  logic [{}:0] {}", p.direction, p.width - 1, p.name)
                } else {
                    format!("    {}  logic {}", p.direction, p.name)
                }
            })
            .collect();
        for (i, line) in port_lines.iter().enumerate() {
            if i < port_lines.len() - 1 {
                writeln!(out, "{line},").unwrap();
            } else {
                writeln!(out, "{line}").unwrap();
            }
        }
    }
    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();

    // Enum typedef
    let variants = state_names.join(", ");
    writeln!(
        out,
        "    typedef enum logic [{width_m1}:0] {{{variants}}} state_t;",
        width_m1 = width.saturating_sub(1)
    )
    .unwrap();
    writeln!(out, "    state_t state;").unwrap();
    writeln!(out).unwrap();

    // Always block
    writeln!(out, "    always_ff @(posedge clk or posedge rst) begin").unwrap();
    writeln!(out, "        if (rst) state <= {initial_name};").unwrap();
    writeln!(out, "        else case (state)").unwrap();

    // Case branches from transitions
    for state_id in controller.states() {
        let source_name = sv_ident(controller.state_name(state_id).unwrap_or("unknown"));

        let outgoing: Vec<(String, String)> = controller
            .outgoing(state_id)
            .iter()
            .map(|t| {
                let target = sv_ident(controller.state_name(t.target()).unwrap_or("unknown"));
                // Collect transition label for comment
                let label = t
                    .labels()
                    .first()
                    .and_then(|lid| controller.label_payload(*lid))
                    .and_then(|payload| payload.first())
                    .cloned()
                    .unwrap_or_default();
                (target, label)
            })
            .collect();

        if outgoing.is_empty() {
            writeln!(
                out,
                "            {source_name}: state <= {source_name}; // no outgoing transitions"
            )
            .unwrap();
        } else if outgoing.len() == 1 {
            let (target, label) = &outgoing[0];
            if label.is_empty() {
                writeln!(out, "            {source_name}: state <= {target};").unwrap();
            } else {
                writeln!(
                    out,
                    "            {source_name}: state <= {target}; // {label}"
                )
                .unwrap();
            }
        } else {
            // Multiple targets — emit as if-else chain with comments
            writeln!(out, "            {source_name}: begin").unwrap();
            for (j, (target, label)) in outgoing.iter().enumerate() {
                if j == 0 {
                    if label.is_empty() {
                        writeln!(out, "                state <= {target};").unwrap();
                    } else {
                        writeln!(out, "                state <= {target}; // {label}").unwrap();
                    }
                }
                // Additional targets noted as comments (strategy picks first)
                if j > 0 {
                    writeln!(out, "                // alt: state <= {target}; // {label}").unwrap();
                }
            }
            writeln!(out, "            end").unwrap();
        }
    }

    writeln!(out, "        endcase").unwrap();
    writeln!(out, "    end").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "endmodule").unwrap();

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_sv_from_synthesis() {
        let ctxdsl = r#"
        context test {
            alphabet { label go; label stop; }
            automata {
                automaton FSM {
                    controllable { label go; label stop; }
                    states { state A initial; state B; }
                    transitions {
                        transition A -> B on label go;
                        transition B -> A on label stop;
                    }
                }
            }
            mu_formulas {
                formula safety { over FSM; body = nu X. ([] X); }
            }
            controllers { controller c { source FSM; satisfying safety; } }
        }
        "#;

        let doc = crate::context_dsl::parse(ctxdsl).unwrap();
        let realized = crate::context_dsl::realize_context(&doc, &[]).unwrap();
        let formula = realized.formulas.get("safety").unwrap();
        let env = realized.environment_for("FSM");
        let synth = realized
            .context
            .synthesise_controller("FSM", &formula.formula, &env, None)
            .unwrap();

        assert!(synth.realizable);
        let sv = controller_to_systemverilog(&synth.controller, "test", true);
        assert!(sv.contains("module test_controller"));
        assert!(sv.contains("typedef enum"));
        assert!(sv.contains("always_ff"));
        assert!(sv.contains("case (state)"));
        assert!(sv.contains("endmodule"));
    }

    #[test]
    fn emit_sv_with_ports() {
        let ctxdsl = r#"
        context test {
            alphabet { label go; }
            automata {
                automaton FSM {
                    controllable { label go; }
                    states { state A initial; state B; }
                    transitions { transition A -> B on label go; }
                }
            }
            mu_formulas {
                formula safety { over FSM; body = nu X. ([] X); }
            }
            controllers { controller c { source FSM; satisfying safety; } }
        }
        "#;

        let doc = crate::context_dsl::parse(ctxdsl).unwrap();
        let realized = crate::context_dsl::realize_context(&doc, &[]).unwrap();
        let formula = realized.formulas.get("safety").unwrap();
        let env = realized.environment_for("FSM");
        let synth = realized
            .context
            .synthesise_controller("FSM", &formula.formula, &env, None)
            .unwrap();

        let ports = vec![
            SvPort {
                name: "clk".to_string(),
                direction: "input",
                width: 1,
            },
            SvPort {
                name: "rst".to_string(),
                direction: "input",
                width: 1,
            },
            SvPort {
                name: "req".to_string(),
                direction: "input",
                width: 1,
            },
            SvPort {
                name: "data".to_string(),
                direction: "input",
                width: 8,
            },
            SvPort {
                name: "ack".to_string(),
                direction: "output",
                width: 1,
            },
        ];

        let sv = controller_to_systemverilog_with_ports(&synth.controller, "test", true, &ports);
        assert!(sv.contains("input  logic clk"));
        assert!(sv.contains("input  logic rst"));
        assert!(sv.contains("input  logic req"));
        assert!(sv.contains("input  logic [7:0] data"));
        assert!(sv.contains("output  logic ack"));
        assert!(sv.contains("endmodule"));
    }

    #[test]
    fn sv_ident_sanitizes_composite_and_illegal_names() {
        // Composite product-state names carry `|`, illegal as SV enum literals.
        assert_eq!(
            sv_ident("Free|Idle|Idle|Idle|Idle"),
            "Free_Idle_Idle_Idle_Idle"
        );
        assert_eq!(sv_ident("Grant0|Holding"), "Grant0_Holding");
        // Leading digit gets a prefix; empty → placeholder; already-legal is unchanged.
        assert_eq!(sv_ident("3state"), "s_3state");
        assert_eq!(sv_ident(""), "s_empty");
        assert_eq!(sv_ident("valid_name_1"), "valid_name_1");
        // Every character of a sanitized name is a legal identifier character.
        assert!(
            sv_ident("a|b.c-d")
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '_')
        );
    }

    #[test]
    fn synthesis_preserves_state_valuations_for_moore_outputs() {
        // The RTL emitter derives Moore outputs from state valuations, so synthesis must
        // carry them onto the controller state (context::mod copies `state_valuation`
        // alongside `state_variables`). Without that copy the controller would have no
        // valuations and the emitter could not tell which output is high in which state.
        let ctxdsl = r#"
        context t {
            alphabet { label go; }
            automata {
                automaton M {
                    controllable { label go; }
                    states {
                        state A initial { valuations { phase = 1; } };
                        state B { valuations { phase = 2; } };
                    }
                    transitions {
                        transition A -> B on label go;
                        transition B -> A on label go;
                    }
                }
            }
            mu_formulas { formula safe { over M; body = nu X. ([] X); } }
            controllers { controller c { source M; satisfying safe; } }
        }
        "#;
        let doc = crate::context_dsl::parse(ctxdsl).unwrap();
        let realized = crate::context_dsl::realize_context(&doc, &[]).unwrap();
        let formula = realized.formulas.get("safe").unwrap();
        let env = realized.environment_for("M");
        let synth = realized
            .context
            .synthesise_controller("M", &formula.formula, &env, None)
            .unwrap();
        assert!(synth.realizable);
        let ctrl = &synth.controller;
        let a = ctrl
            .states()
            .find(|&s| ctrl.state_name(s) == Some("A"))
            .expect("controller has state A");
        let val = ctrl
            .state_valuation(a)
            .expect("state A's valuation was preserved onto the controller");
        assert_eq!(val.get("phase"), Some(&"1".to_string()));
    }
}
