// Generated by Mununu GR(1) synthesis — sound-by-construction (multi-guarantee)
module gr1_controller (input logic clk, input logic p_valid, input logic c_ready, input logic full, input logic empty, output logic enq, output logic deq);
  logic [1:0] mon = 2'd0;
  logic [1:0] mon_next;
  logic [0:0] mode = 1'd0;
  logic [0:0] mode_next;
  logic enq_c;
  logic deq_c;
  always_comb begin
    enq_c = 1'b0;
    deq_c = 1'b0;
    mon_next = mon;
    mode_next = mode;
    unique case ({mode, mon})
      3'd0: begin
        if (!p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && !c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && !c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && c_ready && !full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && !c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && !c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
      end
      3'd1: begin
        if (p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
      end
      3'd2: begin
        if (!p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
      end
      3'd3: begin
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
      end
      3'd4: begin
        if (!p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && !c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && !c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && c_ready && !full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && !c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && !c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && full && empty) begin
          enq_c = 1'b0;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
      end
      3'd5: begin
        if (p_valid && !c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && !c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && !full && empty) begin
          enq_c = 1'b1;
          deq_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
      end
      3'd6: begin
        if (!p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (!p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (p_valid && c_ready && full && !empty) begin
          enq_c = 1'b0;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
      end
      3'd7: begin
        if (p_valid && c_ready && !full && !empty) begin
          enq_c = 1'b1;
          deq_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
      end
      default: ;
    endcase
  end
  assign enq = enq_c;
  assign deq = deq_c;
  always_ff @(posedge clk) begin
    mon <= mon_next;
    mode <= mode_next;
  end
endmodule
