//! Emit a synthesized controller CLTS as GDScript code for Godot Engine.
//!
//! Produces a `class_name` script with:
//! - `enum State` from the controller's state set
//! - Controllable actions as `func name() -> bool` (returns false if blocked)
//! - Uncontrollable events as `func on_name()` (signal handlers)
//! - `get_state_name()` query method

use crate::clts::{Clts, DefaultLabelIdx, DefaultStateIdx};
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fmt::Write;

/// Convert a synthesized controller CLTS to GDScript code.
///
/// `controllable_labels` distinguishes controllable methods (`-> bool`)
/// from uncontrollable event handlers (`on_` prefix, void).
pub fn controller_to_gdscript(
    controller: &Clts<DefaultStateIdx, DefaultLabelIdx>,
    class_name: &str,
    realizable: bool,
    controllable_labels: &HashSet<String>,
) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(
        out,
        "# Generated by Mununu — correct-by-construction controller"
    )
    .unwrap();
    writeln!(out, "# Source: {class_name}").unwrap();
    writeln!(
        out,
        "# Synthesis result: {}",
        if realizable {
            "realizable"
        } else {
            "UNREALIZABLE"
        }
    )
    .unwrap();
    writeln!(out).unwrap();

    if !realizable || controller.state_count() == 0 {
        writeln!(
            out,
            "# The specification cannot be enforced — no controller generated."
        )
        .unwrap();
        return out;
    }

    // Sanitize class name for GDScript identifier
    let gd_class = sanitize_gd_identifier(class_name);

    writeln!(out, "class_name {gd_class}Controller").unwrap();
    writeln!(out, "extends Node").unwrap();
    writeln!(out).unwrap();

    // Collect state names and initial state
    let mut state_names: Vec<String> = Vec::new();
    let mut initial_name = String::new();
    let initials = controller.initial_states();

    for state_id in controller.states() {
        let name = controller
            .state_name(state_id)
            .unwrap_or("UNKNOWN")
            .to_string();
        let gd_name = sanitize_gd_enum_variant(&name);
        if initials.contains(&state_id) && initial_name.is_empty() {
            initial_name = gd_name.clone();
        }
        state_names.push(gd_name);
    }

    // Emit enum State
    writeln!(out, "enum State {{").unwrap();
    for (i, name) in state_names.iter().enumerate() {
        if i < state_names.len() - 1 {
            writeln!(out, "\t{name},").unwrap();
        } else {
            writeln!(out, "\t{name}").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "var current_state: State = State.{initial_name}").unwrap();
    writeln!(out).unwrap();

    // Group transitions by label → per-state targets
    // label_name → [(source_state_name, target_state_name)]
    let mut label_transitions: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    for state_id in controller.states() {
        let source = controller
            .state_name(state_id)
            .unwrap_or("UNKNOWN")
            .to_string();
        let source_gd = sanitize_gd_enum_variant(&source);

        for transition in controller.outgoing(state_id) {
            let target = controller
                .state_name(transition.target())
                .unwrap_or("UNKNOWN")
                .to_string();
            let target_gd = sanitize_gd_enum_variant(&target);

            let label_name = transition
                .labels()
                .first()
                .and_then(|lid| controller.label_payload(*lid))
                .and_then(|payload| payload.first())
                .cloned()
                .unwrap_or_else(|| "unknown".to_string());

            // Skip noop self-loops (they don't represent real actions)
            if label_name == "noop" && source_gd == target_gd {
                continue;
            }

            label_transitions
                .entry(label_name)
                .or_default()
                .push((source_gd.clone(), target_gd));
        }
    }

    // Separate into controllable and uncontrollable
    let mut controllable_funcs: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    let mut uncontrollable_funcs: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    for (label, transitions) in &label_transitions {
        if label == "noop" {
            continue;
        }
        if controllable_labels.contains(label) {
            controllable_funcs.insert(label.clone(), transitions.clone());
        } else {
            uncontrollable_funcs.insert(label.clone(), transitions.clone());
        }
    }

    // Emit controllable actions
    if !controllable_funcs.is_empty() {
        writeln!(
            out,
            "# --- Controllable actions (return false if blocked by controller) ---"
        )
        .unwrap();
        writeln!(out).unwrap();

        for (label, transitions) in &controllable_funcs {
            let func_name = sanitize_gd_identifier(label);
            writeln!(out, "func {func_name}() -> bool:").unwrap();
            writeln!(out, "\tmatch current_state:").unwrap();

            // Deduplicate targets per source
            let unique = deduplicate_transitions(transitions);
            for (source, target) in &unique {
                writeln!(out, "\t\tState.{source}:").unwrap();
                writeln!(out, "\t\t\tcurrent_state = State.{target}").unwrap();
                writeln!(out, "\t\t\treturn true").unwrap();
            }
            writeln!(out, "\t\t_:").unwrap();
            writeln!(out, "\t\t\treturn false").unwrap();
            writeln!(out).unwrap();
        }
    }

    // Emit uncontrollable event handlers
    if !uncontrollable_funcs.is_empty() {
        writeln!(
            out,
            "# --- Uncontrollable events (call from signal handlers / physics) ---"
        )
        .unwrap();
        writeln!(out).unwrap();

        for (label, transitions) in &uncontrollable_funcs {
            let func_name = format!("on_{}", sanitize_gd_identifier(label));
            writeln!(out, "func {func_name}():").unwrap();
            writeln!(out, "\tmatch current_state:").unwrap();

            let unique = deduplicate_transitions(transitions);
            for (source, target) in &unique {
                writeln!(out, "\t\tState.{source}:").unwrap();
                writeln!(out, "\t\t\tcurrent_state = State.{target}").unwrap();
            }
            writeln!(out).unwrap();
        }
    }

    // Query method
    writeln!(out, "# --- Query ---").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "func get_state_name() -> String:").unwrap();
    writeln!(out, "\treturn State.keys()[current_state]").unwrap();

    out
}

/// Collect controllable label names from a CLTS.
pub fn collect_controllable_labels(
    clts: &Clts<DefaultStateIdx, DefaultLabelIdx>,
) -> HashSet<String> {
    let mut labels = HashSet::new();
    for &label_id in clts.controllable_alphabet() {
        if let Some(payload) = clts.label_payload(label_id)
            && let Some(name) = payload.first()
        {
            labels.insert(name.clone());
        }
    }
    labels
}

/// Sanitize a string for use as a GDScript identifier.
fn sanitize_gd_identifier(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    // GDScript identifiers cannot start with a digit
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        out.push_str("_unnamed");
    }
    out
}

/// Sanitize a state name for use as a GDScript enum variant (UPPER_SNAKE_CASE).
fn sanitize_gd_enum_variant(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_alphanumeric() || ch == '_' {
            out.push(ch.to_ascii_uppercase());
        } else if ch == '-' || ch == ' ' || ch == '.' {
            out.push('_');
        }
    }
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        out.push_str("UNKNOWN");
    }
    out
}

/// Deduplicate transitions: keep first target per source state.
fn deduplicate_transitions(transitions: &[(String, String)]) -> Vec<(String, String)> {
    let mut seen: BTreeSet<String> = BTreeSet::new();
    let mut result = Vec::new();
    for (source, target) in transitions {
        if seen.insert(source.clone()) {
            result.push((source.clone(), target.clone()));
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_gdscript_from_synthesis() {
        let ctxdsl = r#"
        context test {
            alphabet { label go; label stop; }
            automata {
                automaton FSM {
                    controllable { label go; }
                    states { state A initial; state B; }
                    transitions {
                        transition A -> B on label go;
                        transition B -> A on label stop;
                    }
                }
            }
            mu_formulas {
                formula safety { over FSM; body = nu X. ([] X); }
            }
            controllers { controller c { source FSM; satisfying safety; } }
        }
        "#;

        let doc = crate::context_dsl::parse(ctxdsl).unwrap();
        let realized = crate::context_dsl::realize_context(&doc, &[]).unwrap();
        let formula = realized.formulas.get("safety").unwrap();
        let env = realized.environment_for("FSM");
        let synth = realized
            .context
            .synthesise_controller("FSM", &formula.formula, &env, None)
            .unwrap();

        assert!(synth.realizable);

        let controllable = collect_controllable_labels(&synth.controller);
        let gd = controller_to_gdscript(&synth.controller, "FSM", true, &controllable);

        assert!(
            gd.contains("class_name FSMController"),
            "missing class_name: {gd}"
        );
        assert!(gd.contains("enum State"), "missing enum: {gd}");
        assert!(gd.contains("var current_state"), "missing var: {gd}");
        assert!(gd.contains("match current_state"), "missing match: {gd}");
        assert!(gd.contains("func "), "missing func: {gd}");
        assert!(gd.contains("get_state_name"), "missing query method: {gd}");
        assert!(gd.contains("realizable"), "missing synthesis result: {gd}");
    }

    #[test]
    fn emit_gdscript_unrealizable() {
        let empty = crate::clts::Clts::builder().build().unwrap();
        let gd = controller_to_gdscript(&empty, "test", false, &HashSet::new());

        assert!(gd.contains("UNREALIZABLE"));
        assert!(!gd.contains("class_name"));
        assert!(!gd.contains("enum State"));
    }

    #[test]
    fn sanitize_identifiers() {
        assert_eq!(sanitize_gd_identifier("ev_attack"), "ev_attack");
        assert_eq!(sanitize_gd_identifier("my-label"), "my_label");
        assert_eq!(sanitize_gd_identifier("123abc"), "_123abc");
        assert_eq!(sanitize_gd_enum_variant("Idle"), "IDLE");
        assert_eq!(sanitize_gd_enum_variant("NoEnemies"), "NOENEMIES");
    }
}
