// Generated by Mununu GR(1) synthesis — sound-by-construction (multi-guarantee)
module gr1_controller (input logic clk, input logic req_0, input logic req_1, output logic grant_0, output logic grant_1);
  logic [1:0] mon = 2'd0;
  logic [1:0] mon_next;
  logic [0:0] mode = 1'd0;
  logic [0:0] mode_next;
  logic grant_0_c;
  logic grant_1_c;
  always_comb begin
    grant_0_c = 1'b0;
    grant_1_c = 1'b0;
    mon_next = mon;
    mode_next = mode;
    unique case ({mode, mon})
      3'd0: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
      end
      3'd1: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd0;
          mode_next = 1'd1;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
      end
      3'd2: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
      end
      3'd3: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b1;
          grant_1_c = 1'b0;
          mon_next = 2'd2;
          mode_next = 1'd1;
        end
      end
      3'd4: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
      end
      3'd5: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
      end
      3'd6: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd0;
          mode_next = 1'd0;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
      end
      3'd7: begin
        if (!req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (req_0 && !req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (!req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
        if (req_0 && req_1) begin
          grant_0_c = 1'b0;
          grant_1_c = 1'b1;
          mon_next = 2'd1;
          mode_next = 1'd0;
        end
      end
      default: ;
    endcase
  end
  assign grant_0 = grant_0_c;
  assign grant_1 = grant_1_c;
  always_ff @(posedge clk) begin
    mon <= mon_next;
    mode <= mode_next;
  end
endmodule
