// Generated by Mununu GR(1) synthesis — sound-by-construction
module gr1_controller (input logic clk, input logic activity, input logic sleep_req, output logic gate);
  logic [0:0] mon = 1'd0;
  logic [0:0] mon_next;
  logic gate_c;
  always_comb begin
    gate_c = 1'b0;
    mon_next = mon;
    unique case (mon)
      1'd0: begin
        if (!activity && !sleep_req) begin
          gate_c = 1'b1;
          mon_next = 1'd0;
        end
        if (activity && !sleep_req) begin
          gate_c = 1'b0;
          mon_next = 1'd0;
        end
        if (!activity && sleep_req) begin
          gate_c = 1'b1;
          mon_next = 1'd0;
        end
        if (activity && sleep_req) begin
          gate_c = 1'b0;
          mon_next = 1'd0;
        end
      end
      1'd1: begin
        if (!activity && !sleep_req) begin
          gate_c = 1'b1;
          mon_next = 1'd0;
        end
        if (activity && !sleep_req) begin
          gate_c = 1'b0;
          mon_next = 1'd1;
        end
        if (!activity && sleep_req) begin
          gate_c = 1'b1;
          mon_next = 1'd0;
        end
        if (activity && sleep_req) begin
          gate_c = 1'b0;
          mon_next = 1'd1;
        end
      end
      default: ;
    endcase
  end
  assign gate = gate_c;
  always_ff @(posedge clk) mon <= mon_next;
endmodule
