//! CMSIS-style C header emission — phase L8 of the principled lift.
//!
//! Takes a parsed [`RegisterMap`](super::register_map::RegisterMap)
//! (from the SVD importer or from a hand-authored sidecar) and emits
//! a CMSIS-DEVICE-style C header that satisfies clang's parse stage
//! for upstream-style firmware code that uses `NRF_TWIM0->TASKS_FOO`
//! struct-member access.
//!
//! Together with the bundled `crates/mununu-core/cmsis-stubs/`
//! directory and the `--cmsis-stubs` CLI flag (added to
//! `mununu codesign extract-c` in this phase), this closes the
//! "parser needs vendor headers" gap that blocked extraction
//! against `upstream/nrfx_twim.c`.
//!
//! ## Scope of phase L8
//!
//! What this *does* cover:
//!   - Self-written driver code in the vendor-style `PERIPH->FIELD`
//!     idiom.
//!   - CMSIS-neutral primitives (`__IO`, `__I`, `__O`, `__NOP`,
//!     `IRQn_Type`, basic NVIC stubs).
//!   - Auto-deriving the register struct layout from the SVD —
//!     same offsets/widths the existing register-map sidecar uses.
//!
//! What this does *not* cover (deferred):
//!   - Arbitrary upstream HAL extraction (e.g.
//!     `upstream/nrfx_twim.c`) — that pulls in vendor-specific
//!     enums, error codes, and helper-function prototypes that the
//!     SVD does not describe. Per-SDK stub packs would close it,
//!     but those are outside L8's scope.
//!   - Bit-field structs inside register unions — the emitter
//!     stops at the register granularity. Users who write
//!     `NRF_TWIM0->INTENSET = 1u << 0` still extract correctly
//!     because the literal is matched against the field's
//!     bit-range in `register_map.json` at the matcher level, not
//!     via struct member access.

use crate::codesign::register_map::{Register, RegisterDirection, RegisterMap};

/// Options for [`emit_cmsis_header`].
#[derive(Debug, Clone, Default)]
pub struct CmsisEmitOptions<'a> {
    /// Vendor prefix prepended to the peripheral name. For Nordic
    /// the canonical prefix is `"NRF_"` so the resulting type is
    /// `NRF_TWIM_Type` and the macro is `NRF_TWIM0`. Empty (the
    /// default) yields the bare peripheral name.
    pub vendor_prefix: &'a str,
    /// Explicit struct type name. When set, overrides the
    /// auto-derived `<vendor_prefix><peripheral>_Type` shape.
    pub struct_type_name: Option<&'a str>,
}

/// Emit a CMSIS-DEVICE-style C header for a single
/// [`RegisterMap`]. The output is one header file's worth of
/// content; the caller is responsible for wrapping it with an
/// include guard if desired (this function emits `#pragma once`).
///
/// The struct layout matches the register-map sidecar's offsets
/// exactly. Padding `uint32_t _reserved<N>[…]` arrays are inserted
/// where the registers are non-contiguous.
pub fn emit_cmsis_header(rm: &RegisterMap, options: &CmsisEmitOptions<'_>) -> String {
    use std::fmt::Write;

    let mut buf = String::new();
    let struct_name = options
        .struct_type_name
        .map(str::to_string)
        .unwrap_or_else(|| {
            format!(
                "{}{}_Type",
                options.vendor_prefix,
                base_name(&rm.peripheral)
            )
        });
    let macro_name = format!("{}{}", options.vendor_prefix, rm.peripheral);

    let _ = writeln!(
        buf,
        "/* Auto-generated by `mununu codesign emit-cmsis-header`. */"
    );
    let _ = writeln!(buf, "/* Source SVD peripheral: {} */", rm.peripheral);
    let _ = writeln!(buf, "/* Base address: {} */", rm.base_address);
    let _ = writeln!(buf, "/* DO NOT EDIT — regenerate from the SVD. */");
    let _ = writeln!(buf, "#pragma once");
    let _ = writeln!(buf, "#include <stdint.h>");
    let _ = writeln!(buf);
    // CMSIS-DEVICE access qualifiers. Conditionally defined so the
    // header co-exists with a real CMSIS install.
    let _ = writeln!(buf, "#ifndef __IO");
    let _ = writeln!(buf, "#define __IO volatile");
    let _ = writeln!(buf, "#endif");
    let _ = writeln!(buf, "#ifndef __I");
    let _ = writeln!(buf, "#define __I  volatile const");
    let _ = writeln!(buf, "#endif");
    let _ = writeln!(buf, "#ifndef __O");
    let _ = writeln!(buf, "#define __O  volatile");
    let _ = writeln!(buf, "#endif");
    let _ = writeln!(buf);

    // Sort registers by offset, emit padding between them.
    let mut sorted: Vec<&Register> = rm.registers.iter().collect();
    sorted.sort_by_key(|r| r.offset);

    let _ = writeln!(buf, "typedef struct {{");
    let mut cursor: u64 = 0;
    let mut reserved_idx: u32 = 0;
    for reg in &sorted {
        if reg.offset > cursor {
            let gap_bytes = reg.offset - cursor;
            let gap_words = gap_bytes / 4;
            let gap_bytes_rem = gap_bytes % 4;
            if gap_words > 0 {
                let _ = writeln!(buf, "    uint32_t _reserved{reserved_idx}[{gap_words}];");
                reserved_idx += 1;
            }
            if gap_bytes_rem > 0 {
                let _ = writeln!(
                    buf,
                    "    uint8_t  _reserved{reserved_idx}_b[{gap_bytes_rem}];"
                );
                reserved_idx += 1;
            }
            cursor = reg.offset;
        }
        let qual = match reg.direction {
            RegisterDirection::Ro => "__I ",
            RegisterDirection::Wo => "__O ",
            RegisterDirection::Rw => "__IO",
        };
        let c_ty = c_type_for_width(reg.width_bits);
        if let Some(desc) = reg.description.as_ref() {
            let one_line: String = desc.replace('\n', " ");
            let _ = writeln!(
                buf,
                "    {qual} {c_ty} {name};  /* 0x{offset:03x}: {desc} */",
                name = reg.name,
                offset = reg.offset,
                desc = one_line
            );
        } else {
            let _ = writeln!(
                buf,
                "    {qual} {c_ty} {name};  /* 0x{offset:03x} */",
                name = reg.name,
                offset = reg.offset
            );
        }
        cursor += u64::from(reg.width_bits / 8);
    }
    let _ = writeln!(buf, "}} {struct_name};");
    let _ = writeln!(buf);
    let _ = writeln!(
        buf,
        "#define {macro_name}_BASE_ADDR {base}UL",
        base = rm.base_address
    );
    let _ = writeln!(
        buf,
        "#define {macro_name}             (({struct_name} *){macro_name}_BASE_ADDR)"
    );
    buf
}

/// Return the C type name for a given register width in bits.
fn c_type_for_width(width_bits: u32) -> &'static str {
    match width_bits {
        8 => "uint8_t ",
        16 => "uint16_t",
        32 => "uint32_t",
        64 => "uint64_t",
        // SVD permits arbitrary widths but CMSIS headers always use
        // the standard sizes. Anything non-standard falls back to
        // uint32_t with a soundness caveat — the matcher uses the
        // offset, not the type, so this is informational only.
        _ => "uint32_t",
    }
}

/// Strip a trailing digit suffix from a peripheral name so
/// `TWIM0` → `TWIM` (the CMSIS-DEVICE convention for the typedef
/// name shared across all peripheral instances).
fn base_name(peripheral: &str) -> String {
    let trimmed: String = peripheral
        .trim_end_matches(|c: char| c.is_ascii_digit())
        .to_string();
    if trimmed.is_empty() {
        peripheral.to_string()
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codesign::register_map::{
        AccessPath, Field, Register, RegisterDirection, RegisterMap, VisibilityClass,
    };

    fn twim_register_map() -> RegisterMap {
        RegisterMap {
            peripheral: "TWIM0".to_string(),
            base_address: "0x40003000".to_string(),
            description: None,
            contract_uri: None,
            registers: vec![
                Register {
                    name: "TASKS_STARTRX".to_string(),
                    offset: 0,
                    width_bits: 32,
                    direction: RegisterDirection::Wo,
                    visibility_class: VisibilityClass::Control,
                    access_path: AccessPath::MmioDirect,
                    description: Some("Start RX sequence".to_string()),
                    fields: vec![],
                },
                Register {
                    name: "TASKS_STARTTX".to_string(),
                    offset: 8,
                    width_bits: 32,
                    direction: RegisterDirection::Wo,
                    visibility_class: VisibilityClass::Control,
                    access_path: AccessPath::MmioDirect,
                    description: None,
                    fields: vec![],
                },
                Register {
                    name: "ENABLE".to_string(),
                    offset: 0x500,
                    width_bits: 32,
                    direction: RegisterDirection::Rw,
                    visibility_class: VisibilityClass::Control,
                    access_path: AccessPath::MmioDirect,
                    description: None,
                    fields: vec![Field {
                        name: "ENABLE".to_string(),
                        bits: [0, 3],
                        sv_signal: None,
                        c_accessor: None,
                        description: None,
                    }],
                },
            ],
        }
    }

    #[test]
    fn emits_struct_with_register_fields_in_offset_order() {
        let header = emit_cmsis_header(&twim_register_map(), &CmsisEmitOptions::default());
        assert!(header.contains("typedef struct"));
        assert!(header.contains("TASKS_STARTRX"));
        assert!(header.contains("TASKS_STARTTX"));
        assert!(header.contains("ENABLE"));
        // TASKS_STARTRX (offset 0) → TASKS_STARTTX (offset 8): one word of padding.
        assert!(header.contains("_reserved0[1]"));
    }

    #[test]
    fn vendor_prefix_applied_to_macro_and_type_name() {
        let header = emit_cmsis_header(
            &twim_register_map(),
            &CmsisEmitOptions {
                vendor_prefix: "NRF_",
                ..Default::default()
            },
        );
        assert!(header.contains("typedef struct"));
        assert!(header.contains("NRF_TWIM_Type"));
        assert!(header.contains("#define NRF_TWIM0"));
        assert!(header.contains("NRF_TWIM0_BASE_ADDR 0x40003000UL"));
    }

    #[test]
    fn override_struct_type_name_takes_precedence() {
        let header = emit_cmsis_header(
            &twim_register_map(),
            &CmsisEmitOptions {
                vendor_prefix: "NRF_",
                struct_type_name: Some("MyCustomType"),
            },
        );
        assert!(header.contains("} MyCustomType;"));
        assert!(header.contains("(MyCustomType *)"));
    }

    #[test]
    fn read_only_register_uses_io_qualifier() {
        let mut rm = twim_register_map();
        rm.registers.push(Register {
            name: "STATUS".to_string(),
            offset: 0x600,
            width_bits: 32,
            direction: RegisterDirection::Ro,
            visibility_class: VisibilityClass::Status,
            access_path: AccessPath::MmioDirect,
            description: None,
            fields: vec![],
        });
        let header = emit_cmsis_header(&rm, &CmsisEmitOptions::default());
        // The STATUS register is RO → __I qualifier.
        assert!(header.contains("__I  uint32_t STATUS"));
    }

    #[test]
    fn base_name_strips_trailing_digits() {
        assert_eq!(base_name("TWIM0"), "TWIM");
        assert_eq!(base_name("TWIM"), "TWIM");
        assert_eq!(base_name("SPI3"), "SPI");
        assert_eq!(base_name(""), "");
        // All-digit peripheral name (unlikely) keeps original.
        assert_eq!(base_name("123"), "123");
    }

    #[test]
    fn header_includes_pragma_once_and_stdint() {
        let header = emit_cmsis_header(&twim_register_map(), &CmsisEmitOptions::default());
        assert!(header.contains("#pragma once"));
        assert!(header.contains("#include <stdint.h>"));
    }
}
