#!/usr/bin/env bash
# regenerate-ctxdsl.sh — re-run `mununu codesign extract-c` against
# the self-contained firmware.c / firmware_buggy.c in this
# directory and overwrite firmware.ctxdsl / firmware_buggy.ctxdsl
# with the extractor's output.
#
# The byte-deterministic, real-clang evidence for the README's
# verification claims. Per CLAUDE.md claims-integrity rule #10,
# this script's output is the canonical CTXDSL — the hand-
# authored variants are preserved at
# `firmware.hand_authored.ctxdsl` and
# `firmware_buggy.hand_authored.ctxdsl` for reference.
#
# Usage (from repo root):
#   ./examples/industrial/codesign_nrf52_twim_i2c/regenerate-ctxdsl.sh

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

DIR="examples/industrial/codesign_nrf52_twim_i2c"
REG="$DIR/register_map.json"
# Always rebuild the debug binary so the script reflects the current
# tree's extractor — stale release binaries lurking from earlier
# builds have bitten us. Use --quiet to keep the output clean.
cargo build --quiet --bin mununu
MUNUNU="target/debug/mununu"

# Emit the synthesised CTXDSL for one C source. Each function's
# automaton becomes one `automata { automaton ... }` block; the
# Driver dispatcher composes them.
emit_ctxdsl() {
    local source="$1"
    local label="$2"
    local source_basename
    source_basename="$(basename "$source")"
    local json_tmp
    json_tmp="$(mktemp)"
    "$MUNUNU" codesign extract-c "$source" \
        --register-map "$REG" \
        --synthesize-automaton \
        --driver-mode 2>/dev/null \
        | grep -v "Logging initialized" \
        > "$json_tmp"
    SOURCE_BASENAME="$source_basename" LABEL="$label" JSON_TMP="$json_tmp" python3 <<'PY'
import json, os, sys
with open(os.environ['JSON_TMP']) as fh:
    data = json.load(fh)
src = os.environ['SOURCE_BASENAME']
label = os.environ['LABEL']
print(f'// Auto-extracted CTXDSL from {src} — Nordic nRF52840 TWIM0 ({label}).')
print('// =========================================================================')
print('//')
print('// REGENERATED by regenerate-ctxdsl.sh — do not hand-edit this file.')
print('// Each function in the C source becomes one automaton; the Driver')
print('// automaton dispatches non-deterministically to each public entry')
print('// point. Synthesised on the rendezvous-label alphabet emitted by')
print('// mununu codesign couple from register_map.json.')
print('//')
print('// CLAIMS-INTEGRITY RULE #10: this is real-clang extractor output.')
print('// The original hand-authored variant lives at')
print('// firmware.hand_authored.ctxdsl (and firmware_buggy.hand_authored.ctxdsl)')
print('// for reference; their mu_formulas reference the hand-authored state')
print('// names (Idle, Polling, Sending, …) and are NOT carried over here.')
print('// The synthesised states (S0, S1, Loop0, …, Calling_<fn>) differ.')
print('//')
print('// SOUNDNESS posture:')
print('//   - Linear bodies extract faithfully.')
print('//   - Polling loops (while (cond)) detected at IR level and emitted')
print('//     as Loop_i states with same-label enter/iterate/exit transitions.')
print('//   - Bit-field RMW sequences collapsed to single per-field writes.')
print('//   - External calls + L5/L5.5 inline pointer-parameter aliases.')
print('//   - Anything beyond these patterns surfaces as a structured warning,')
print('//     not silent.')
print()
print('context CoupledNrfTwimFirmware {')
print()
for f in data['functions']:
    ctxdsl = f.get('automaton_ctxdsl')
    if ctxdsl:
        sys.stdout.write(ctxdsl)
        print()
if data.get('driver_ctxdsl'):
    sys.stdout.write(data['driver_ctxdsl'])
    print()
print('}')
PY
    rm -f "$json_tmp"
}

emit_ctxdsl "$DIR/firmware.c" "I2C driver" > "$DIR/firmware.ctxdsl"
emit_ctxdsl "$DIR/firmware_buggy.c" "I2C driver, planted-bug variant" > "$DIR/firmware_buggy.ctxdsl"

printf 'wrote %s (%d lines)\n' "$DIR/firmware.ctxdsl" "$(wc -l < "$DIR/firmware.ctxdsl" | tr -d ' ')"
printf 'wrote %s (%d lines)\n' "$DIR/firmware_buggy.ctxdsl" "$(wc -l < "$DIR/firmware_buggy.ctxdsl" | tr -d ' ')"
